
root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/."
delay = 1000
exclude_regex = [".*_templ.go"]
exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
include_dir = []
exclude_file = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
poll = true

include_ext = ["go", "tpl", "tmpl", "templ", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
