services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    command: >
      sh -c "air -c .air.toml"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  data:
